### ISSUE TITLE
Align the footer section

### ISSUE THREAD

**Issue by Suman373** [Suman373/CryptoCatalogue#4]
The newsletter portion is out of alignment.
Align the button with the email input field.
Make sure to take snapshots of ur results, include them in your PR.
You are requested to use your local machine for the changes.

**Comment by parush-uppal** [comment]
Hi, would like to work on the issue can you please assign it to me?

**Comment by Suman373** [comment]
@parush-uppal Make sure to put ur snapshots of result in the PR. Go ahead!
